name: Coverity Central Analysis (Self hosted)

on: [workflow_dispatch]

jobs:
  Coverity-Central:
    runs-on: self-hosted

    env:
      COVERITY_URL: https://local.cim.com
      COVERITY_USERNAME: ${{ secrets.COVERITY_USERNAME }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_PROJECT: $GITHUB_REPO
      COVERITY_CHECKERS: --webapp-security

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Initialize project and stream
        run: |
          COVERITY_PROJECT_NAME=`echo $COVERITY_PROJECT | tr '/' '-'`
          COVERITY_STREAM_NAME="$COVERITY_PROJECT_NAME"-${GITHUB_REF##*/}
          echo INFO: Coverity project name: $COVERITY_PROJECT_NAME
          echo INFO: Coverity stream name: $COVERITY_STREAM_NAME
          cov-manage-im --url $COVERITY_URL --user $COVERITY_USERNAME --mode projects --add --set name:"$COVERITY_PROJECT_NAME" --set description:"$COVERITY_PROJECT_NAME"
          cov-manage-im --url $COVERITY_URL --user $COVERITY_USERNAME --mode streams --add --set name:"$COVERITY_STREAM_NAME" --set description:"$COVERITY_STREAM_NAME"
          cov-manage-im --url $COVERITY_URL --user $COVERITY_USERNAME --mode projects --update --name "$COVERITY_PROJECT_NAME" --insert stream:"$COVERITY_STREAM_NAME"
        continue-on-error: true

      - name: Coverity full scan
        run: |
          COVERITY_PROJECT_NAME=`echo $COVERITY_PROJECT | tr '/' '-'`
          COVERITY_STREAM_NAME="$COVERITY_PROJECT_NAME"-${GITHUB_REF##*/}
          echo INFO: Coverity project name: $COVERITY_PROJECT_NAME
          echo INFO: Coverity stream name: $COVERITY_STREAM_NAME
          cov-capture --project-dir . --dir idir
          cov-analyze --dir idir --ticker-mode none --strip-path $GITHUB_WORKSPACE $CHECKERS
          cov-commit-defects --dir idir --ticker-mode none --url $COVERITY_URL --stream "$COVERITY_STREAM_NAME" --scm git --description "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" --target $RUNNER_OS --version $GITHUB_SHA

      - name: Coverity security gate
        run: |
          curl -fLsS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/api/viewContents/issues/v1/OWASP%20Web%20Top%2010?projectId=$COVERITY_PROJECT_NAME > results.json
          if [ $(cat results.json | jq .viewContentsV1.totalRows) -ne 0 ]; then cat results.json | jq .viewContentsV1.rows; exit 1; fi
